<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <title>Sales Report History</title>
    <style>
        body {
            background-color: white !important;
            color: black !important;
            font-family: Arial, sans-serif;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            font-size: 10px;
        }
        th, td {
            border: 1px solid #333;
            padding: 8px;
            text-align: center;
            color: black !important;
        }
        @media print {
            button, .btn {
                display: none !important;
            }
        }
        h2, p {
            color: black !important;
            text-align: center;
        }
        .container {
            max-width: 900px;
            margin: 0 auto;
            padding: 10px;
        }
        .btn {
            background-color: #007bff;
            color: white;
            border: none;
            padding: 8px 14px;
            cursor: pointer;
            font-size: 14px;
            border-radius: 4px;
        }
        .btn:hover {
            background-color: #0056b3;
        }
        .float-right {
            float: right;
            margin-top: 20px;
        }
    </style>
</head>
<body>

<div id="salesReportContent" class="container">
    <h2>Sales Transaction History</h2>
    <p><strong>Generated by:</strong> {{ $user->employee_firstname }} {{ $user->employee_lastname }}</p>

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Transaction ID</th>
                <th>Processed by</th>
                <th>Type</th>
                <th>Debit</th>
                <th>Credit</th>
                <th>Balance</th>
            </tr>
        </thead>
        <tbody>
            @php
                $totalDebit = 0;
                $totalCredit = 0;
                $lastBalance = 0;
            @endphp

            @foreach($transactions as $trx)
                @php
                    $totalDebit += $trx->debit;
                    $totalCredit += $trx->credit;
                    $lastBalance = $trx->balances;
                @endphp
                <tr>
                    <td>{{ \Carbon\Carbon::parse($trx->transaction_date)->format('Y-m-d') }}</td>
                    <td>{{ $trx->transaction_id }}</td>
                    <td>{{ ucfirst($trx->process_by) }}</td>
                    <td>{{ ucfirst($trx->transaction_type) }}</td>
                    <td>₱{{ number_format($trx->debit, 2) }}</td>
                    <td>₱{{ number_format($trx->credit, 2) }}</td>
                    <td>₱{{ number_format($trx->balances, 2) }}</td>
                </tr>
            @endforeach

            <tr style="font-weight: bold;">
                <td colspan="4">TOTAL</td>
                <td>₱{{ number_format($totalDebit, 2) }}</td>
                <td>₱{{ number_format($totalCredit, 2) }}</td>
                <td>₱{{ number_format($lastBalance, 2) }}</td>
            </tr>
        </tbody>
    </table>

    <div class="float-right">
        <button id="backButton" onclick="window.location.href='/admin/sales/report'" class="btn btn-info">Back</button>
        <button id="exportButton" class="btn" onclick="confirmPinBeforePrint()">Print / Download</button>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"></script>

<script>
    function confirmPinBeforePrint() {
        Swal.fire({
            title: 'Enter Your PIN',
            input: 'password',
            inputAttributes: {
                autocapitalize: 'off',
                maxlength: 6
            },
            showCancelButton: true,
            confirmButtonText: 'Confirm',
            showLoaderOnConfirm: true,
            preConfirm: (pin) => {
                if (!pin) {
                    Swal.showValidationMessage('Please enter your PIN');
                    return false;
                }
                return fetch('/admin/sales/validate-pin', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRF-TOKEN': '{{ csrf_token() }}'
                    },
                    body: JSON.stringify({ pin: pin })
                })
                .then(async response => {
                    if (!response.ok) {
                        const errorData = await response.json();
                        throw new Error(errorData.message || 'Invalid PIN');
                    }
                    return response.json();
                })
                .catch(error => {
                    Swal.showValidationMessage(`PIN validation failed: ${error.message}`);
                });
            },
            allowOutsideClick: () => !Swal.isLoading()
        }).then((result) => {
            if (result.isConfirmed) {
                const exportButton = document.getElementById('exportButton');
                const backButton = document.getElementById('backButton');
                const element = document.getElementById('salesReportContent');

                // Hide both buttons before export
                exportButton.style.display = 'none';
                backButton.style.display = 'none';

                const opt = {
                    margin: 0.5,
                    filename: 'Sales_Report_{{ date("Ymd_His") }}.pdf',
                    image: { type: 'jpeg', quality: 0.98 },
                    html2canvas: { scale: 2 },
                    jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' }
                };

                html2pdf().from(element).set(opt).save().then(() => {
                    // Show buttons after export
                    exportButton.style.display = 'inline-block';
                    backButton.style.display = 'inline-block';
                });
            }
        });
    }
</script>

</body>
</html>
