<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <title>Sales Report History</title>
    <style>
        body {
            background-color: white !important;
            color: black !important;
            font-family: Arial, sans-serif;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            font-size: 10px;
        }
        th, td {
            border: 1px solid #333;
            padding: 8px;
            text-align: center;
            color: black !important;
        }
        @media print {
            button, .btn {
                display: none !important;
            }
        }
        h2, p {
            color: black !important;
            text-align: center;
        }
        .container {
            max-width: 900px;
            margin: 0 auto;
            padding: 10px;
        }
        .btn {
            background-color: #007bff;
            color: white;
            border: none;
            padding: 8px 14px;
            cursor: pointer;
            font-size: 14px;
            border-radius: 4px;
        }
        .btn:hover {
            background-color: #0056b3;
        }
        .float-right {
            float: right;
            margin-top: 20px;
        }
    </style>
</head>
<body>

<div id="salesReportContent" class="container">
    <h2>Sales Transaction History</h2>
    <p><strong>Generated by:</strong> {{ $user->employee_firstname }} {{ $user->employee_lastname }}</p>

                                  @php
                                        $totalDebit = 0;
                                        $totalCredit = 0;
                                        $totalStockInBalance = DB::table('sales_transactions')
                                            ->where('transaction_type', 'stock in')
                                            ->sum('balances');
                                    @endphp

                                    <table class="table table-bordered table-responsive-sm">
                                        <thead>
                                            <tr>
                                                <th style="color: #A16D28;">Transaction date</th>
                                                <th style="color: #A16D28;">Process by</th>
                                                <th style="color: #A16D28;">Transaction type</th>
                                                <th style="color: #A16D28;">Transaction ID</th>
                                                <th style="color: #A16D28;">Debit</th>
                                                <th style="color: #A16D28;">Credit</th>
                                                <th style="color: #A16D28;">Balances</th>
                                            </tr>
                                        </thead>

                                        <tbody>
                                            @foreach ($stockInSalesTransaction as $transaction)
                                                @php
                                                    $totalDebit += $transaction->debit;
                                                    $totalCredit += $transaction->credit;
                                                @endphp
                                                <tr>
                                                    <td>{{ $transaction->transaction_date }}</td>
                                                    <td>{{ $transaction->process_by }}</td>
                                                    <td><span style="text-transform: capitalize">{{ $transaction->transaction_type }}</span></td>
                                                    <td>{{ $transaction->transaction_id }}</td>
                                                    <td>{{ number_format($transaction->debit, 2) }}</td>
                                                    <td>{{ number_format($transaction->credit, 2) }}</td>
                                                    <td>{{ number_format($transaction->balances, 2) }}</td>
                                                </tr>
                                            @endforeach
                                        </tbody>

                                        <tfoot>
                                            <tr style="color: black">
                                                <td colspan="4" style="text-align: center; font-weight: bold;">Sub-total</td>
                                                <td style="font-weight: bold;">{{ number_format($totalDebit, 2) }}</td>
                                                <td style="font-weight: bold;">{{ number_format($totalCredit, 2) }}</td>
                                                <td style="font-weight: bold;">{{ number_format($totalStockInBalance, 2) }}</td>
                                            </tr>
                                        </tfoot>
                                    </table>


                                    @php
                                        $runningDebit = 0;
                                        $runningCredit = 0;
                                        $runningBalance = 0;

                                        $sortedTransactions = $allSalesTransactions->sortBy(function ($transaction) {
                                            return match ($transaction->transaction_type) {
                                                'return-item' => 2, // show last
                                                'payment' => 1,     // show second last
                                                default => 0,       // show first
                                            };
                                        });
                                    @endphp

                                    <table class="table table-bordered table-responsive-sm mt-2">
                                        <thead>
                                            <tr>
                                                <th style="color: #A16D28;">Transaction date</th>
                                                <th style="color: #A16D28;">Process by</th>
                                                <th style="color: #A16D28;">Transaction type</th>
                                                <th style="color: #A16D28;">Transaction ID</th>
                                                <th style="color: #A16D28;">Debit</th>
                                                <th style="color: #A16D28;">Credit</th>
                                                <th style="color: #A16D28;">Balance</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach ($sortedTransactions as $transaction)
                                                @php
                                                    // accumulate totals
                                                    $runningDebit += $transaction->debit;
                                                    $runningCredit += $transaction->credit;

                                                    // formula: previous balance + debit - credit
                                                    $runningBalance += $transaction->debit - $transaction->credit;
                                                @endphp
                                                <tr>
                                                    <td>{{ $transaction->transaction_date }}</td>
                                                    <td>{{ $transaction->process_by }}</td>
                                                    <td>{{ ucfirst($transaction->transaction_type) }}</td>
                                                    <td>{{ $transaction->transaction_id }}</td>
                                                    <td>{{ number_format($transaction->debit, 2) }}</td>
                                                    <td>{{ number_format($transaction->credit, 2) }}</td>
                                                    <td>{{ number_format($runningBalance, 2) }}</td>
                                                </tr>
                                            @endforeach
                                        </tbody>
                                        <tfoot>
                                            <tr style="color: black">
                                                <td colspan="4" style="text-align: center; font-weight: bold;">Sub-total</td>
                                                <td class="font-weight-bold">{{ number_format($runningDebit, 2) }}</td>
                                                <td class="font-weight-bold">{{ number_format($runningCredit, 2) }}</td>
                                                <td class="font-weight-bold">{{ number_format($runningBalance, 2) }}</td>
                                            </tr>
                                        </tfoot>
                                    </table>



                                        @php
                                            $totalLoss = 0;
                                        @endphp

                                        <table class="table table-bordered table-responsive-sm mt-2">
                                            <thead>
                                                <tr>
                                                    <th style="color: #A16D28;">Transaction date</th>
                                                    <th style="color: #A16D28;">Process by</th>
                                                    <th style="color: #A16D28;">Transaction type</th>
                                                    <th style="color: #A16D28;">Transaction ID</th>
                                                    <th style="color: #A16D28;">Loss</th>
                                                    <th style="color: #A16D28;">Debit</th>
                                                    <th style="color: #A16D28;">Credit</th>
                                                    <th style="color: #A16D28;">Balance</th>
                                                </tr>
                                            </thead>
                                        <tbody>
                                            @foreach ($allSalesTransactions as $transaction)
                                                @if ($transaction->loss > 0)
                                                    @php $totalLoss += $transaction->loss; @endphp
                                                    <tr>
                                                        <td>{{ $transaction->transaction_date }}</td>
                                                        <td>{{ $transaction->process_by }}</td>
                                                        <td>{{ ucfirst($transaction->transaction_type) }}</td>
                                                        <td>{{ $transaction->transaction_id }}</td>
                                                        <td style="color: red; font-weight: bold;">
                                                            {{ number_format($transaction->loss, 2) }}
                                                        </td>
                                                        <td>0.00</td>
                                                        <td>0.00</td>
                                                        <td>{{ number_format($transaction->loss, 2) }}</td>
                                                    </tr>
                                                @endif
                                            @endforeach
                                        </tbody>

                                        <tfoot>
                                            <tr style="color: black">
                                                <td colspan="4" style="text-align: center; font-weight: bold;">Total Loss</td>
                                                <td class="font-weight-bold text-danger">{{ number_format($totalLoss, 2) }}</td>
                                                <td>{{ number_format(0, 2) }}</td>
                                                <td>{{ number_format(0, 2) }}</td>
                                                <td class="font-weight-bold text-danger">{{ number_format($totalLoss, 2) }}</td>
                                            </tr>
                                        </tfoot>
                                        </table>

                                        @php
                                            $totalProfit = $runningCredit - $totalDebit - $totalLoss;
                                        @endphp

                                        <table class="table table-bordered table-responsive-sm mt-2">
                                            <tfoot>
                                                <tr>
                                                    <td colspan="7" class="text-right font-weight-bold" style="color: green; font-size: 16px;">
                                                        Total Profit
                                                    </td>
                                                    <td class="font-weight-bold" style="color: green; font-size: 16px;">
                                                        {{ number_format($totalProfit, 2) }}
                                                    </td>
                                                </tr>
                                            </tfoot>
                                        </table>

    <div class="float-right">
        <button id="backButton" onclick="window.location.href='/manager/sales/report'" class="btn btn-info">Back</button>
        <button id="exportButton" class="btn" onclick="confirmPinBeforePrint()">Print / Download</button>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"></script>

<script>
    function confirmPinBeforePrint() {
        Swal.fire({
            title: 'Enter Your PIN',
            input: 'password',
            inputAttributes: {
                autocapitalize: 'off',
                maxlength: 6
            },
            showCancelButton: true,
            confirmButtonText: 'Confirm',
            showLoaderOnConfirm: true,
            preConfirm: (pin) => {
                if (!pin) {
                    Swal.showValidationMessage('Please enter your PIN');
                    return false;
                }
                return fetch('/manager/sales/validate-pin', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRF-TOKEN': '{{ csrf_token() }}'
                    },
                    body: JSON.stringify({ pin: pin })
                })
                .then(async response => {
                    if (!response.ok) {
                        const errorData = await response.json();
                        throw new Error(errorData.message || 'Invalid PIN');
                    }
                    return response.json();
                })
                .catch(error => {
                    Swal.showValidationMessage(`PIN validation failed: ${error.message}`);
                });
            },
            allowOutsideClick: () => !Swal.isLoading()
        }).then((result) => {
            if (result.isConfirmed) {
                const exportButton = document.getElementById('exportButton');
                const backButton = document.getElementById('backButton');
                const element = document.getElementById('salesReportContent');

                // Hide both buttons before export
                exportButton.style.display = 'none';
                backButton.style.display = 'none';

                const opt = {
                    margin: 0.5,
                    filename: 'Sales_Report_{{ date("Ymd_His") }}.pdf',
                    image: { type: 'jpeg', quality: 0.98 },
                    html2canvas: { scale: 2 },
                    jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' }
                };

                html2pdf().from(element).set(opt).save().then(() => {
                    // Show buttons after export
                    exportButton.style.display = 'inline-block';
                    backButton.style.display = 'inline-block';
                });
            }
        });
    }
</script>

</body>
</html>
